openapi: 3.0.0 # OpenAPI-Version (erlaubte Features und Syntax)
info: # Allgemeine Infos zur Schnittstelle
  title: EDI@Energy API-Webdienste zur Ermittlung der MaLo-ID der Marktlokation
  version: 2.0.0
  description: Mit diesen API-Webdiensten wir die Ermittlung der MaLo-ID der Marktlokation umgesestzt.

servers: # URLs unter der die API bereitsteht
  - url: https://github.com/EDI-Energy
    description: GitHub-Server der EDI@Energy

paths:
  /maloId/request/v2:
    post:
      summary: Anfrage MaLo-ID der Marktlokation
      description: Anfrage MaLo-ID der Marktlokation
      operationId: uploadFile
      parameters:
      - name: transactionId
        in: header
        description: Externe Transaktions-Id zur eindeutigen Identifikation der Anfrage der MaLo-ID der Marktlokation des sendenden Marktpartners.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/transactionId.yaml#/components/schemas/transactionId'
      - name: creationDateTime
        in: header
        description: Zeitpunkt an dem der Aufruf erstellt wurde
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/creationDateTime.yaml#/components/schemas/creationDateTime'
      - name: initialTransactionId
        in: header
        description: Zur Angabe des Idempotenzschlüssels im Falle eines Retry.
        required: false
        style: simple
        explode: false
        schema:
          $ref: '../../schema/initialTransactionId.yaml#/components/schemas/initialTransactionId'
      requestBody:
        content:
         application/json:
           schema:
             $ref: '../../schema/identificationParameter.yaml#/components/schemas/identificationParameter'
      responses:
        "202":
          description: accepted
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "405":
          description: Method not allowed
        "500":
          description: Internal Server Error
  /maloId/dataForMarketLocationNegative/v2:
    post:
      summary: Negative Rückmeldung auf die Anfrage der MaLo-ID der Marktlokation.
      description: Negative Rückmeldung auf die Anfrage der MaLo-ID der Marktlokation.
      parameters:
      - name: transactionId
        in: header
        description: Externe Transaktions-Id zur eindeutigen Identifikation der negativen Rückmeldung auf die Anfrage der MaLo-ID der Marktlokation des sendenden Marktpartners.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/transactionId.yaml#/components/schemas/transactionId'
      - name: creationDateTime
        in: header
        description: Zeitpunkt an dem der Aufruf erstellt wurde
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/creationDateTime.yaml#/components/schemas/creationDateTime'
      - name: initialTransactionId
        in: header
        description: Zur Angabe des Idempotenzschlüssels im Falle eines Retry.
        required: false
        style: simple
        explode: false
        schema:
          $ref: '../../schema/initialTransactionId.yaml#/components/schemas/initialTransactionId'
      - name: referenceId
        in: query
        description: "Externe Vorgangsreferenz zur eindeutigen Identifikation des ursprünglichen Aufrufs (Wert aus transactionId, Schritt1 des UC Ermittlung der MaLo-ID der Marktlokation)."
        required: true
        style: form
        explode: false
        schema:
          $ref: '../../schema/referenceId.yaml#/components/schemas/referenceId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../schema/resultNegative.yaml#/components/schemas/resultNegative'   
      responses:
        "202":
          description: accepted
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "405":
          description: Method not allowed
        "500":
          description: Internal Server Error

  /maloId/dataForMarketLocationPositive/v2:
    post:
      summary: Postive Rückmeldung auf die Anfrage der MaLo-ID der Marktlokation.
      description: Postive Rückmeldung auf die Anfrage der MaLo-ID der Marktlokation.
      parameters:
      - name: transactionId
        in: header
        description: Externe Transaktions-Id zur eindeutigen Identifikation der postiven Rückmeldung auf die Anfrage der MaLo-ID der Marktlokation des sendenden Marktpartners.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/transactionId.yaml#/components/schemas/transactionId'
      - name: creationDateTime
        in: header
        description: Zeitpunkt an dem der Aufruf erstellt wurde
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/creationDateTime.yaml#/components/schemas/creationDateTime'
      - name: initialTransactionId
        in: header
        description: Zur Angabe des Idempotenzschlüssels im Falle eines Retry.
        required: false
        style: simple
        explode: false
        schema:
          $ref: '../../schema/initialTransactionId.yaml#/components/schemas/initialTransactionId'
      - name: referenceId
        in: query
        description: "Externe Vorgangsreferenz zur eindeutigen Identifikation der ursprünglichen Anfrage (Wert aus transactionId, Schritt1 des UC Ermittlung der MaLo-ID der Marktlokation)."
        required: true
        style: form
        explode: false
        schema:
          $ref: '../../schema/referenceId.yaml#/components/schemas/referenceId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../schema/resultPositive.yaml#/components/schemas/resultPositive'
      responses:
        "202":
          description: accepted
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "405":
          description: Method not allowed
        "500":
          description: Internal Server Error
