name: pull request build (redocly)

on:
  pull_request:
    branches: [ main, 20*-consultation ]

jobs:
  pullrequest-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Redocly
        run: npm i -g @redocly/cli@latest

      - name: Validate OpenAPI definition
        run: redocly lint $(find ./api -type f)
